require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealSetsController do

  # This should return the minimal set of attributes required to create a valid
  # DealSet. As you add validations to DealSet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "fecha_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DealSetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all deal_sets as @deal_sets" do
      deal_set = DealSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:deal_sets).should eq([deal_set])
    end
  end

  describe "GET show" do
    it "assigns the requested deal_set as @deal_set" do
      deal_set = DealSet.create! valid_attributes
      get :show, {:id => deal_set.to_param}, valid_session
      assigns(:deal_set).should eq(deal_set)
    end
  end

  describe "GET new" do
    it "assigns a new deal_set as @deal_set" do
      get :new, {}, valid_session
      assigns(:deal_set).should be_a_new(DealSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested deal_set as @deal_set" do
      deal_set = DealSet.create! valid_attributes
      get :edit, {:id => deal_set.to_param}, valid_session
      assigns(:deal_set).should eq(deal_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DealSet" do
        expect {
          post :create, {:deal_set => valid_attributes}, valid_session
        }.to change(DealSet, :count).by(1)
      end

      it "assigns a newly created deal_set as @deal_set" do
        post :create, {:deal_set => valid_attributes}, valid_session
        assigns(:deal_set).should be_a(DealSet)
        assigns(:deal_set).should be_persisted
      end

      it "redirects to the created deal_set" do
        post :create, {:deal_set => valid_attributes}, valid_session
        response.should redirect_to(DealSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deal_set as @deal_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealSet.any_instance.stub(:save).and_return(false)
        post :create, {:deal_set => { "fecha_id" => "invalid value" }}, valid_session
        assigns(:deal_set).should be_a_new(DealSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealSet.any_instance.stub(:save).and_return(false)
        post :create, {:deal_set => { "fecha_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deal_set" do
        deal_set = DealSet.create! valid_attributes
        # Assuming there are no other deal_sets in the database, this
        # specifies that the DealSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DealSet.any_instance.should_receive(:update_attributes).with({ "fecha_id" => "1" })
        put :update, {:id => deal_set.to_param, :deal_set => { "fecha_id" => "1" }}, valid_session
      end

      it "assigns the requested deal_set as @deal_set" do
        deal_set = DealSet.create! valid_attributes
        put :update, {:id => deal_set.to_param, :deal_set => valid_attributes}, valid_session
        assigns(:deal_set).should eq(deal_set)
      end

      it "redirects to the deal_set" do
        deal_set = DealSet.create! valid_attributes
        put :update, {:id => deal_set.to_param, :deal_set => valid_attributes}, valid_session
        response.should redirect_to(deal_set)
      end
    end

    describe "with invalid params" do
      it "assigns the deal_set as @deal_set" do
        deal_set = DealSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => deal_set.to_param, :deal_set => { "fecha_id" => "invalid value" }}, valid_session
        assigns(:deal_set).should eq(deal_set)
      end

      it "re-renders the 'edit' template" do
        deal_set = DealSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => deal_set.to_param, :deal_set => { "fecha_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deal_set" do
      deal_set = DealSet.create! valid_attributes
      expect {
        delete :destroy, {:id => deal_set.to_param}, valid_session
      }.to change(DealSet, :count).by(-1)
    end

    it "redirects to the deal_sets list" do
      deal_set = DealSet.create! valid_attributes
      delete :destroy, {:id => deal_set.to_param}, valid_session
      response.should redirect_to(deal_sets_url)
    end
  end

end
