require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiaController do

  # This should return the minimal set of attributes required to create a valid
  # Dium. As you add validations to Dium, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "location_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiaController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dia as @dia" do
      dium = Dium.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dia).should eq([dium])
    end
  end

  describe "GET show" do
    it "assigns the requested dium as @dium" do
      dium = Dium.create! valid_attributes
      get :show, {:id => dium.to_param}, valid_session
      assigns(:dium).should eq(dium)
    end
  end

  describe "GET new" do
    it "assigns a new dium as @dium" do
      get :new, {}, valid_session
      assigns(:dium).should be_a_new(Dium)
    end
  end

  describe "GET edit" do
    it "assigns the requested dium as @dium" do
      dium = Dium.create! valid_attributes
      get :edit, {:id => dium.to_param}, valid_session
      assigns(:dium).should eq(dium)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dium" do
        expect {
          post :create, {:dium => valid_attributes}, valid_session
        }.to change(Dium, :count).by(1)
      end

      it "assigns a newly created dium as @dium" do
        post :create, {:dium => valid_attributes}, valid_session
        assigns(:dium).should be_a(Dium)
        assigns(:dium).should be_persisted
      end

      it "redirects to the created dium" do
        post :create, {:dium => valid_attributes}, valid_session
        response.should redirect_to(Dium.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dium as @dium" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dium.any_instance.stub(:save).and_return(false)
        post :create, {:dium => { "location_id" => "invalid value" }}, valid_session
        assigns(:dium).should be_a_new(Dium)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dium.any_instance.stub(:save).and_return(false)
        post :create, {:dium => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dium" do
        dium = Dium.create! valid_attributes
        # Assuming there are no other dia in the database, this
        # specifies that the Dium created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dium.any_instance.should_receive(:update_attributes).with({ "location_id" => "1" })
        put :update, {:id => dium.to_param, :dium => { "location_id" => "1" }}, valid_session
      end

      it "assigns the requested dium as @dium" do
        dium = Dium.create! valid_attributes
        put :update, {:id => dium.to_param, :dium => valid_attributes}, valid_session
        assigns(:dium).should eq(dium)
      end

      it "redirects to the dium" do
        dium = Dium.create! valid_attributes
        put :update, {:id => dium.to_param, :dium => valid_attributes}, valid_session
        response.should redirect_to(dium)
      end
    end

    describe "with invalid params" do
      it "assigns the dium as @dium" do
        dium = Dium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dium.any_instance.stub(:save).and_return(false)
        put :update, {:id => dium.to_param, :dium => { "location_id" => "invalid value" }}, valid_session
        assigns(:dium).should eq(dium)
      end

      it "re-renders the 'edit' template" do
        dium = Dium.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dium.any_instance.stub(:save).and_return(false)
        put :update, {:id => dium.to_param, :dium => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dium" do
      dium = Dium.create! valid_attributes
      expect {
        delete :destroy, {:id => dium.to_param}, valid_session
      }.to change(Dium, :count).by(-1)
    end

    it "redirects to the dia list" do
      dium = Dium.create! valid_attributes
      delete :destroy, {:id => dium.to_param}, valid_session
      response.should redirect_to(dia_url)
    end
  end

end
