require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FechasController do

  # This should return the minimal set of attributes required to create a valid
  # Fecha. As you add validations to Fecha, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "location_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FechasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all fechas as @fechas" do
      fecha = Fecha.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fechas).should eq([fecha])
    end
  end

  describe "GET show" do
    it "assigns the requested fecha as @fecha" do
      fecha = Fecha.create! valid_attributes
      get :show, {:id => fecha.to_param}, valid_session
      assigns(:fecha).should eq(fecha)
    end
  end

  describe "GET new" do
    it "assigns a new fecha as @fecha" do
      get :new, {}, valid_session
      assigns(:fecha).should be_a_new(Fecha)
    end
  end

  describe "GET edit" do
    it "assigns the requested fecha as @fecha" do
      fecha = Fecha.create! valid_attributes
      get :edit, {:id => fecha.to_param}, valid_session
      assigns(:fecha).should eq(fecha)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fecha" do
        expect {
          post :create, {:fecha => valid_attributes}, valid_session
        }.to change(Fecha, :count).by(1)
      end

      it "assigns a newly created fecha as @fecha" do
        post :create, {:fecha => valid_attributes}, valid_session
        assigns(:fecha).should be_a(Fecha)
        assigns(:fecha).should be_persisted
      end

      it "redirects to the created fecha" do
        post :create, {:fecha => valid_attributes}, valid_session
        response.should redirect_to(Fecha.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fecha as @fecha" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fecha.any_instance.stub(:save).and_return(false)
        post :create, {:fecha => { "location_id" => "invalid value" }}, valid_session
        assigns(:fecha).should be_a_new(Fecha)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fecha.any_instance.stub(:save).and_return(false)
        post :create, {:fecha => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fecha" do
        fecha = Fecha.create! valid_attributes
        # Assuming there are no other fechas in the database, this
        # specifies that the Fecha created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fecha.any_instance.should_receive(:update_attributes).with({ "location_id" => "1" })
        put :update, {:id => fecha.to_param, :fecha => { "location_id" => "1" }}, valid_session
      end

      it "assigns the requested fecha as @fecha" do
        fecha = Fecha.create! valid_attributes
        put :update, {:id => fecha.to_param, :fecha => valid_attributes}, valid_session
        assigns(:fecha).should eq(fecha)
      end

      it "redirects to the fecha" do
        fecha = Fecha.create! valid_attributes
        put :update, {:id => fecha.to_param, :fecha => valid_attributes}, valid_session
        response.should redirect_to(fecha)
      end
    end

    describe "with invalid params" do
      it "assigns the fecha as @fecha" do
        fecha = Fecha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fecha.any_instance.stub(:save).and_return(false)
        put :update, {:id => fecha.to_param, :fecha => { "location_id" => "invalid value" }}, valid_session
        assigns(:fecha).should eq(fecha)
      end

      it "re-renders the 'edit' template" do
        fecha = Fecha.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fecha.any_instance.stub(:save).and_return(false)
        put :update, {:id => fecha.to_param, :fecha => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fecha" do
      fecha = Fecha.create! valid_attributes
      expect {
        delete :destroy, {:id => fecha.to_param}, valid_session
      }.to change(Fecha, :count).by(-1)
    end

    it "redirects to the fechas list" do
      fecha = Fecha.create! valid_attributes
      delete :destroy, {:id => fecha.to_param}, valid_session
      response.should redirect_to(fechas_url)
    end
  end

end
