require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReservationSetsController do

  # This should return the minimal set of attributes required to create a valid
  # ReservationSet. As you add validations to ReservationSet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "fecha_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReservationSetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reservation_sets as @reservation_sets" do
      reservation_set = ReservationSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reservation_sets).should eq([reservation_set])
    end
  end

  describe "GET show" do
    it "assigns the requested reservation_set as @reservation_set" do
      reservation_set = ReservationSet.create! valid_attributes
      get :show, {:id => reservation_set.to_param}, valid_session
      assigns(:reservation_set).should eq(reservation_set)
    end
  end

  describe "GET new" do
    it "assigns a new reservation_set as @reservation_set" do
      get :new, {}, valid_session
      assigns(:reservation_set).should be_a_new(ReservationSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested reservation_set as @reservation_set" do
      reservation_set = ReservationSet.create! valid_attributes
      get :edit, {:id => reservation_set.to_param}, valid_session
      assigns(:reservation_set).should eq(reservation_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ReservationSet" do
        expect {
          post :create, {:reservation_set => valid_attributes}, valid_session
        }.to change(ReservationSet, :count).by(1)
      end

      it "assigns a newly created reservation_set as @reservation_set" do
        post :create, {:reservation_set => valid_attributes}, valid_session
        assigns(:reservation_set).should be_a(ReservationSet)
        assigns(:reservation_set).should be_persisted
      end

      it "redirects to the created reservation_set" do
        post :create, {:reservation_set => valid_attributes}, valid_session
        response.should redirect_to(ReservationSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reservation_set as @reservation_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationSet.any_instance.stub(:save).and_return(false)
        post :create, {:reservation_set => { "fecha_id" => "invalid value" }}, valid_session
        assigns(:reservation_set).should be_a_new(ReservationSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationSet.any_instance.stub(:save).and_return(false)
        post :create, {:reservation_set => { "fecha_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reservation_set" do
        reservation_set = ReservationSet.create! valid_attributes
        # Assuming there are no other reservation_sets in the database, this
        # specifies that the ReservationSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ReservationSet.any_instance.should_receive(:update_attributes).with({ "fecha_id" => "1" })
        put :update, {:id => reservation_set.to_param, :reservation_set => { "fecha_id" => "1" }}, valid_session
      end

      it "assigns the requested reservation_set as @reservation_set" do
        reservation_set = ReservationSet.create! valid_attributes
        put :update, {:id => reservation_set.to_param, :reservation_set => valid_attributes}, valid_session
        assigns(:reservation_set).should eq(reservation_set)
      end

      it "redirects to the reservation_set" do
        reservation_set = ReservationSet.create! valid_attributes
        put :update, {:id => reservation_set.to_param, :reservation_set => valid_attributes}, valid_session
        response.should redirect_to(reservation_set)
      end
    end

    describe "with invalid params" do
      it "assigns the reservation_set as @reservation_set" do
        reservation_set = ReservationSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservation_set.to_param, :reservation_set => { "fecha_id" => "invalid value" }}, valid_session
        assigns(:reservation_set).should eq(reservation_set)
      end

      it "re-renders the 'edit' template" do
        reservation_set = ReservationSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ReservationSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => reservation_set.to_param, :reservation_set => { "fecha_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reservation_set" do
      reservation_set = ReservationSet.create! valid_attributes
      expect {
        delete :destroy, {:id => reservation_set.to_param}, valid_session
      }.to change(ReservationSet, :count).by(-1)
    end

    it "redirects to the reservation_sets list" do
      reservation_set = ReservationSet.create! valid_attributes
      delete :destroy, {:id => reservation_set.to_param}, valid_session
      response.should redirect_to(reservation_sets_url)
    end
  end

end
